package com.Denfop;

import java.io.File;

import com.google.common.collect.Sets;

import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.registry.GameData;
import java.util.Set;
import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.ItemBlock;
import net.minecraftforge.common.config.Configuration;

public class Config {
public static final boolean EnglishFix = false;
public static boolean EnableNetherOres;
public static int limit;
public static int tier;
public static int neutrongenday;
public static int neutronGenNight;
public static int neutronStorage;
public static int neutronOutput;
public static int InfinityGenNight;
public static int InfinityGenDay;
public static int InfinityOutput;
public static int InfinityStorage;
public static int manasteeltier;
public static int manasteeloutput;
public static int manasteelstorage;
public static int manasteelgennight;
public static int manasteelgenday;
public static int elementiumstorage;
public static int elementiumgenday;
public static int elementiumgennight;
public static int elementiumoutput;
public static int elementiumtier;
public static int terasteelgenday;
public static int terasteelgennight;
public static int terasteelstorage;
public static int terasteeloutput;
public static int terasteeltier;
public static int chaosgenday;
public static int chaosgennight;
public static int chaosstorage;
public static int chaosoutput;
public static int chaostier;
public static int awakenedtier;
public static int awakenedoutput;
public static int awakenedstorage;
public static int awakenedgennight;
public static int awakenedgenday;
public static int draconictier;
public static int draconicoutput;
public static int draconicstorage;
public static int draconicgennight;
public static int draconicgenday;
public static boolean ASP;
public static int toriyRodCells;
public static int toriyRodHeat;
public static float toriyPower;
public static File configFile;
public static boolean registerDraconicPanels;
public static boolean registerChaosArmour;
public static boolean registerChaosFluxCapacitor;
public static boolean registerChaosAxe;
public static boolean registerChaosBow;
public static boolean registerChaosSword;
public static boolean registerChaosShovel;
public static boolean registerChaosPickaxe;
public static boolean registerChaosDestructionStaff;
public static boolean nightvision;
public static float effPower;
public static float bigHolePower;
public static int spectralsaberactive;
public static int spectralsabernotactive;
public static int Storagequantumsuit;
public static int neutronpanelGenDay;
public static int neutronpanelOutput;
public static int neutronpanelGenNight;
public static int neutronpanelStorage;
public static int Radius3;
public static int durability3;
public static int efficiency3;
public static int minWindStrength3;
public static int maxWindStrength3;
public static int Radius4;
public static int durability4;
public static int efficiency4;
public static int minWindStrength4;
public static int maxWindStrength4;
public static int Radius5;
public static int durability5;
public static int efficiency5;
public static int maxWindStrength5;
public static int minWindStrength5;
public static int protonOutput;
public static int protontier;
public static int protongenDay;
public static int protongennitht;
public static boolean wireless;
public static int spectralsaber;
public static int spectralsaber1;
public static int enegry1;
public static int storage1;
public static int tier1;
public static int energy;
public static int enegry2;
public static int storage2;
public static int tier2;
public static boolean disableeffect;
public static boolean disableeffect1;
public static boolean disableeffect2;
public static boolean disableeffect3;
public static boolean disableeffect4;
public static boolean disableeffect5;
public static boolean disable;
public static boolean disable1;
public static boolean disable2;
public static boolean disable3;
public static boolean disable4;
public static float lowPower;
public static float ultraLowPower;
public static int ultdrillmaxCharge;
public static int ultdrilltier;
public static int energyPerOperation;
public static int energyPerLowOperation;
public static int energyPerultraLowPowerOperation;
public static int energyPerbigHolePowerOperation;
public static int ultdrilltransferLimit;
public static boolean enableefficiency;
public static int efficiencylevel;
public static int advGenDay;
public static boolean AvaritiaLoaded;
public static boolean BotaniaLoaded;
public static boolean AE2Loaded;
public static boolean Draconic;
public static  boolean Botania;
public static boolean Avaritia;
public static boolean enableefficiency1;
public static int efficiencylevel1;
public static boolean enablesilkTouch;
public static boolean enablefortune;
public static int fortunelevel;
public static boolean enableexlposion;
public static boolean enableIC2EasyMode;
public static boolean EnableEndOres;
public static boolean EnableMickailOre;
public static boolean EnableSpinelOre;
public static boolean EnablePlatiumOre;
public static boolean EnableWolframOre;
public static boolean EnableChromiumOre;
public static boolean EnableIridiumOre;
public static boolean EnableMagnesiumOre;
public static boolean EnableNickelOre;
public static boolean EnableToriyOre;
public static boolean EnableMagnetitOre;
public static boolean damagecable;
public static boolean newsystem;
public static int armor_maxcharge;
public static int armor_transferlimit;
public static int armor_tier;
public static int armor_maxcharge_body;
public static int percent_output;
public static int percent_storage;
public static int percent_day;
public static int percent_night;
public static int spectralpanelGenDay;
public static int spectralpanelGenNight;
public static int singularpanelGenDay;
public static int singularpanelOutput;
public static int spectralpanelOutput;
public static int singularpanelGenNight;
public static int adminpanelGenDay;
public static int adminpanelGenNight;
public static int AdminpanelStorage;
public static int AdminpanelOutput;
public static int photonicpanelGenDay;
public static int photonicpanelGenNight;
public static int photonicpanelOutput;
public static int photonicpanelStorage;
public static int tier2_MFSU;
public static int tier_Saber;
public static int tier3_MFSU;
public static int singularpanelstorage;
public static int singularpaneltier;
public static int spectralpaneltier;
public static int adminpaneltier;
public static int photonicpaneltier;
public static int neutronpaneltier;
public static boolean thaumcraft;
public static int advGenNight;
public static int advStorage;
public static int advOutput;
public static int hGenDay;
public static int hGenNight;
public static int hStorage;
public static int hOutput;
public static int uhGenDay;
public static int uhGenNight;
public static int uhStorage;
public static int uhOutput;
public static int qpGenDay;
public static int qpGenNight;
public static int qpStorage;
public static int qpOutput;
public static int qgbaseProduction;
public static int qgbaseMaxPacketSize;
public static int spectralpanelstorage;
public static boolean disableAdvancedSolarHelmetRecipe;
public static boolean disableHybridSolarHelmetRecipe;
public static boolean disableUltimateSolarHelmetRecipe;
public static boolean disableAdvancedSolarPanelRecipe;
public static boolean disableHybridSolarPanelRecipe;
public static boolean disableUltimateSolarPanelRecipe;
public static boolean disableQuantumSolarPanelRecipe;
public static boolean disableMolecularTransformerRecipe;
public static boolean disableDoubleSlabRecipe;
public static boolean enableSimpleAdvancedSolarPanelRecipes;
public static boolean enableHardRecipes;
//

public static int maxCharge;
public static int transferLimit;
public static boolean EnchantingPlus;
public static  boolean MineFactory;
 public static int Radius;
 public static int durability;
 public static int efficiency;
 public static int minWindStrength;
 public static int maxWindStrength;
 public static int Radius1;
 public static int durability1;
 public static int efficiency1;
 public static int minWindStrength1;
 public static int maxWindStrength1;
 public static int Radius2;
 public static int durability2;
 public static int efficiency2;
 public static int minWindStrength2;
 public static int maxWindStrength2;
public static int MaxChangesaber;
public static int transferLimitsaber;
public static int tiersaber;
public static int Quantumsaberactive;
public static int Quantumsabernotactive;
public static boolean Streak;
public static int TerrasteelRodCells;
public static int TerrasteelRodHeat;
public static float TerrasteelPower;
public static int ProtonRodHeat;
public static int ProtonRodCells;
public static float ProtonPower;
public static boolean DraconicLoaded;
 public static int spectralsaberactive1;
 public static int spectralsabernotactive1;
 public static int maxCharge1;
public static int transferLimit1;
public static String configFileName;
public static int storage_limit;

public static int  molecular;
public static int  molecular1; 
public static int  molecular2; 
public static int  molecular3; 
public static int  molecular4; 
public static int  molecular5; 
public static int  molecular6; 
public static int  molecular7; 
public static int  molecular8; 
public static int  molecular9; 
public static int molecular10; 
public static int molecular11 ; 
public static int  molecular12; 
public static int  molecular13; 
public static int  molecular14; 
public static int  molecular15; 
public static int  molecular16; 
public static int  molecular17; 
public static int  molecular18; 
public static int  molecular19; 
public static int  molecular20;
public static int  molecular21; 
public static int  molecular22; 
public static int  molecular23; 
public static int  molecular24; 
public static int  molecular25; 
public static int  molecular26; 
public static int  molecular27; 
public static int  molecular28; 
public static int  molecular29; 
public static int  molecular30; 
public static int  molecular31; 
public static int  molecular32; 
public static int  molecular33; 
public static int  molecular34; 
public static int  molecular35;
public static int enerycost;
public static int expstorage;
public static boolean recipemolecular; 
public static boolean recipemolecular1; 
public static boolean recipemolecular2; 
public static boolean recipemolecular3; 
public static boolean recipemolecular4; 
public static boolean recipemolecular5; 
public static boolean recipemolecular6; 
public static boolean recipemolecular7; 
public static boolean recipemolecular9; 
public static boolean recipemolecular8; 
public static boolean recipemolecular10; 
public static boolean recipemolecular11; 
public static boolean recipemolecular12; 
public static boolean recipemolecular13; 
public static boolean recipemolecular14; 
public static boolean recipemolecular15; 
public static boolean recipemolecular16; 
public static boolean recipemolecular17; 
public static boolean recipemolecular18; 
public static boolean recipemolecular19; 
public static boolean recipemolecular20; 
public static boolean recipemolecular21; 
public static boolean recipemolecular22; 
public static boolean recipemolecular23; 
public static boolean recipemolecular24; 
public static boolean recipemolecular25; 
public static boolean recipemolecular26; 
public static boolean recipemolecular27; 
public static boolean recipemolecular28; 
public static boolean recipemolecular29; 
public static boolean recipemolecular30; 
public static boolean recipemolecular31; 
public static boolean recipemolecular32; 
public static boolean recipemolecular33; 
public static boolean recipemolecular34; 
public static boolean recipemolecular35;
public static boolean recipemolecular36;

public static int molecular36;
public static void config(final FMLPreInitializationEvent event) {
	final Configuration config = new Configuration(event.getSuggestedConfigurationFile());
     try {
         config.load();
         configFile = event.getSuggestedConfigurationFile();
        //
         expstorage=config.get("Basic Mechanisms", "exp storage", 500).getInt(500);
         enerycost=config.get("Quantum Querry", "energy consume", 35000).getInt(35000);
         molecular=config.get("Crafts Molecular Transformer", "Wither Skeleton skull", 1000000).getInt(1000000);
         molecular1=config.get("Crafts Molecular Transformer", "Nether Star", 150000000).getInt(150000000);
         molecular2=config.get("Crafts Molecular Transformer", "Iridium Ore", 5000000).getInt(5000000);
         molecular3=config.get("Crafts Molecular Transformer", "Proton", 7500000).getInt(7500000);
         molecular4=config.get("Crafts Molecular Transformer", "Iridium ingot", 1000000).getInt(1000000);
         molecular5=config.get("Crafts Molecular Transformer", "Photon ingot", 8000000).getInt(8000000);
         molecular6=config.get("Crafts Molecular Transformer", "Gunpowder", 50000).getInt(50000);
         molecular7=config.get("Crafts Molecular Transformer", "Gravel", 25000).getInt(25000);
         molecular8=config.get("Crafts Molecular Transformer", "Diamond", 700000).getInt(700000);
         molecular9=config.get("Crafts Molecular Transformer", "Nickel ingot", 250000).getInt(250000);
         molecular10=config.get("Crafts Molecular Transformer", "Gold ingot", 250000).getInt(250000);
         molecular11=config.get("Crafts Molecular Transformer", "Silver ingot", 450000).getInt(450000);
         molecular12=config.get("Crafts Molecular Transformer", "Tungsten ingot", 400000).getInt(400000);
         molecular13=config.get("Crafts Molecular Transformer", "Spinel ingot", 500000).getInt(500000);
         molecular14=config.get("Crafts Molecular Transformer", "Mikhalov ingot", 500000).getInt(500000);
         molecular15=config.get("Crafts Molecular Transformer", "Chromium ingot", 450000).getInt(450000);
         molecular16=config.get("Crafts Molecular Transformer", "Platium ingot", 600000).getInt(600000);
         molecular17=config.get("Crafts Molecular Transformer", "Advanced ingot", 1500).getInt(1500);
         molecular18=config.get("Crafts Molecular Transformer", "Hybrid core", 7500).getInt(7500);
         molecular19=config.get("Crafts Molecular Transformer", "Ultimate core", 40000).getInt(40000);
         molecular20=config.get("Crafts Molecular Transformer", "Quantum core", 90000).getInt(90000);
         molecular21=config.get("Crafts Molecular Transformer", "Spectral core", 150000).getInt(150000);
         molecular22=config.get("Crafts Molecular Transformer", "Proton core", 205000).getInt(205000);
         molecular23=config.get("Crafts Molecular Transformer", "Singular core", 275000).getInt(275000);
         molecular24=config.get("Crafts Molecular Transformer", "Difraction core", 400000).getInt(400000);
         molecular25=config.get("Crafts Molecular Transformer", "Photnic core", 800000).getInt(800000);
         molecular26=config.get("Crafts Molecular Transformer", "Sintezator", 1000000000).getInt(1000000000);
         molecular27=config.get("Crafts Molecular Transformer", "Sun lense", 15000000).getInt(15000000);
         molecular28=config.get("Crafts Molecular Transformer", "Rain lense", 15000000).getInt(15000000);
         molecular29=config.get("Crafts Molecular Transformer", "Nether lense", 15000000).getInt(15000000);
         molecular30=config.get("Crafts Molecular Transformer", "Night lense", 15000000).getInt(15000000);
         molecular31=config.get("Crafts Molecular Transformer", "Earth lense", 15000000).getInt(15000000);
         molecular32=config.get("Crafts Molecular Transformer", "End lense", 15000000).getInt(15000000);
         molecular33=config.get("Crafts Molecular Transformer", "Aer lense", 15000000).getInt(15000000);
         molecular34=config.get("Crafts Molecular Transformer", "Photon", 750000).getInt(750000);
         molecular35=config.get("Crafts Molecular Transformer", "Magnesium ingot", 450000).getInt(450000);
         molecular36=config.get("Crafts Molecular Transformer", "Caravkiy ingot", 750000).getInt(750000);
         
         recipemolecular=config.get("Enable Crafts Molecular Transformer", "Wither Skeleton skull", true).getBoolean(true);
         recipemolecular1=config.get("Enable Crafts Molecular Transformer", "Nether Star", true).getBoolean(true);
         recipemolecular2=config.get("Enable Crafts Molecular Transformer", "Iridium Ore", true).getBoolean(true);
         recipemolecular3=config.get("Enable Crafts Molecular Transformer", "Proton", true).getBoolean(true);
         recipemolecular4=config.get("Enable Crafts Molecular Transformer", "Iridium ingot", true).getBoolean(true);
         recipemolecular5=config.get("Enable Crafts Molecular Transformer", "Photon ingot", true).getBoolean(true);
         recipemolecular6=config.get("Enable Crafts Molecular Transformer", "Gunpowder", true).getBoolean(true);
         recipemolecular7=config.get("Enable Crafts Molecular Transformer", "Gravel", true).getBoolean(true);
         recipemolecular8=config.get("Enable Crafts Molecular Transformer", "Diamond", true).getBoolean(true);
         recipemolecular9=config.get("Enable Crafts Molecular Transformer", "Nickel ingot", true).getBoolean(true);
         recipemolecular10=config.get("Enable Crafts Molecular Transformer", "Gold ingot", true).getBoolean(true);
         recipemolecular11=config.get("Enable Crafts Molecular Transformer", "Silver ingot", true).getBoolean(true);
         recipemolecular12=config.get("Enable Crafts Molecular Transformer", "Tungsten ingot", true).getBoolean(true);
         recipemolecular13=config.get("Enable Crafts Molecular Transformer", "Spinel ingot", true).getBoolean(true);
         recipemolecular14=config.get("Enable Crafts Molecular Transformer", "Mikhalov ingot", true).getBoolean(true);
         recipemolecular15=config.get("Enable Crafts Molecular Transformer", "Chromium ingot", true).getBoolean(true);
         recipemolecular16=config.get("Enable Crafts Molecular Transformer", "Platium ingot", true).getBoolean(true);
         recipemolecular17=config.get("Enable Crafts Molecular Transformer", "Advanced ingot", true).getBoolean(true);
         recipemolecular18=config.get("Enable Crafts Molecular Transformer", "Hybrid core", true).getBoolean(true);
         recipemolecular19=config.get("Enable Crafts Molecular Transformer", "Ultimate core", true).getBoolean(true);
         recipemolecular20=config.get("Enable Crafts Molecular Transformer", "Quantum core", true).getBoolean(true);
         recipemolecular21=config.get("Enable Crafts Molecular Transformer", "Spectral core", true).getBoolean(true);
         recipemolecular22=config.get("Enable Crafts Molecular Transformer", "Proton core", true).getBoolean(true);
         recipemolecular23=config.get("Enable Crafts Molecular Transformer", "Singular core", true).getBoolean(true);
         recipemolecular24=config.get("Enable Crafts Molecular Transformer", "Difraction core", true).getBoolean(true);
         recipemolecular25=config.get("Enable Crafts Molecular Transformer", "Photnic core", true).getBoolean(true);
         recipemolecular26=config.get("Enable Crafts Molecular Transformer", "Sintezator", true).getBoolean(true);
         recipemolecular27=config.get("Enable Crafts Molecular Transformer", "Sun lense", true).getBoolean(true);
         recipemolecular28=config.get("Enable Crafts Molecular Transformer", "Rain lense", true).getBoolean(true);
         recipemolecular29=config.get("Enable Crafts Molecular Transformer", "Nether lense", true).getBoolean(true);
         recipemolecular30=config.get("Enable Crafts Molecular Transformer", "Night lense", true).getBoolean(true);
         recipemolecular31=config.get("Enable Crafts Molecular Transformer", "Earth lense", true).getBoolean(true);
         recipemolecular32=config.get("Enable Crafts Molecular Transformer", "End lense", true).getBoolean(true);
         recipemolecular33=config.get("Enable Crafts Molecular Transformer", "Aer lense", true).getBoolean(true);
         recipemolecular34=config.get("Enable Crafts Molecular Transformer", "Photon", true).getBoolean(true);
         recipemolecular35=config.get("Enable Crafts Molecular Transformer", "Magnesium ingot", true).getBoolean(true);
         recipemolecular36=config.get("Enable Crafts Molecular Transformer", "Caravkiy ingot", true).getBoolean(true);
         //
         storage_limit=config.get("Module", "Limit in energy storage", 2).getInt(2);
         damagecable=config.get("Events", "Damage", true).getBoolean(true);
         newsystem=config.get("Events", "New system transfer energy", true).getBoolean(true);
         EnableMagnetitOre=config.get("Generation", "Spawn Magnetit Ore", true).getBoolean(true);
         EnableToriyOre=config.get("Generation", "Spawn Toriy Ore", true).getBoolean(true);
         EnableNickelOre=config.get("Generation", "Spawn Nickel Ore", true).getBoolean(true);
         EnableMagnesiumOre=config.get("Generation", "Spawn Magnesium Ore", true).getBoolean(true);
         EnableIridiumOre=config.get("Generation", "Spawn Iridium Ore", true).getBoolean(true);
         EnableChromiumOre=config.get("Generation", "Spawn Chromium Ore", true).getBoolean(true);
         EnableWolframOre=config.get("Generation", "Spawn Wolfram Ore", true).getBoolean(true);
         EnablePlatiumOre=config.get("Generation", "Spawn Platium Ore", true).getBoolean(true);
         EnableSpinelOre=config.get("Generation", "Spawn Spinel Ore", true).getBoolean(true);
         EnableMickailOre=config.get("Generation", "Spawn Mickail Ore", true).getBoolean(true);
         effPower= config.get("UltimateDrill", "Mode 0 efficiency", 35).getInt(35); 
         lowPower=config.get("UltimateDrill", "Mode 1 efficiency", 20).getInt(20); 
         bigHolePower =config.get("UltimateDrill", "Mode 2 efficiency", 16).getInt(16); 
         ultraLowPower=config.get("UltimateDrill", "Mode 3 efficiency", 10).getInt(10); 
         ultdrillmaxCharge=config.get("UltimateDrill", "maxCharge", 750000).getInt(750000); 
         ultdrilltier=config.get("UltimateDrill", "tier", 2).getInt(2); 
         ultdrilltransferLimit=config.get("UltimateDrill", "transfer Limit", 500).getInt(500); 
         energyPerOperation=config.get("UltimateDrill", "energyPerOperation", 160).getInt(160); 
         energyPerLowOperation=config.get("UltimateDrill", "energyPerLowOperation", 80).getInt(80); 
         energyPerbigHolePowerOperation=config.get("UltimateDrill", "energyPerBigHolesOperation",300).getInt(300); 
         energyPerultraLowPowerOperation=config.get("UltimateDrill", "energyPerUltraBigHolesOperation", 500).getInt(500); 
         enableefficiency=config.get("UltimateDrill", "Enable Efficiency tool mode 0", true).getBoolean(true); 
         if(efficiencylevel > 1 && efficiencylevel <15) {
         efficiencylevel=config.get("UltimateDrill", "Level efficiency(tool mode 0)", 10).getInt(10); }else {
        	 efficiencylevel =10;
         }
         EnableNetherOres=config.get("Generation", "Spawn ores in Nether", true).getBoolean(true);
         EnableEndOres=config.get("Generation", "Spawn ores in End", true).getBoolean(true);
         enableIC2EasyMode=config.get("general", "Easy Mode", false).getBoolean(false);
         
         enableexlposion=config.get("Events", "Enable exlposion", true).getBoolean(true);
         if(damagecable == false) {
        	 newsystem = true;
         }
         enableefficiency=config.get("UltimateDrill", "Enable Efficiency tool mode 1", true).getBoolean(true); 
         if(efficiencylevel1 > 1 && efficiencylevel1 <15) {
         efficiencylevel1=config.get("UltimateDrill", "Level efficiency(tool mode 1)", 10).getInt(10); }else {
        	 efficiencylevel1 =10;
         }
         enablesilkTouch=config.get("UltimateDrill", "Enable silk Touch tool mode 2", true).getBoolean(true); 
         enablefortune=config.get("UltimateDrill", "Enable fortune tool mode 3", true).getBoolean(true); 
         if(fortunelevel > 1 && fortunelevel < 10) {
         fortunelevel=config.get("UltimateDrill", "Level fortune(tool mode 3)", 5).getInt(5); }else {
        	 fortunelevel = 5;
         }
         //
         singularpanelstorage = config.get("Singular Solar panel", "SingularSPStorage", 10000000).getInt(10000000); 
         configFileName = event.getSuggestedConfigurationFile().getAbsolutePath();
        spectralpanelGenDay = config.get("Spectral Solar panel", "SpectralSPGenDay", 2560).getInt(2560);
         protongenDay = config.get("Proton Solar panel", "ProtonGenDay", 10240).getInt(10240);
         protongennitht = config.get("Proton Solar panel", "ProtonGenNight", 5120).getInt(5120);
         protonOutput = config.get("Proton Solar panel", "ProtonOutput", 20480).getInt(20480);
         protontier = config.get("Proton Solar panel", "Protonstorage", 5000000).getInt(5000000);
         spectralpanelGenNight = config.get("Spectral Solar panel", "SpectralSPGenNight", 1280).getInt(1280);
         singularpanelGenDay = config.get("Singular Solar panel", "SingularSPGenDay", 40960).getInt(40960);
         singularpanelGenNight = config.get("Singular Solar panel", "SingularSPGenNight", 40960).getInt(40960);
         singularpanelOutput = config.get("Singular Solar panel", "SingularSPOutput", 81920).getInt(81920);
         spectralpanelOutput = config.get("Spectral Solar panel", "SpectralSPOutput", 5120).getInt(5120);
         adminpanelGenDay = config.get("Light-Adbord Solar panel", "AdminPanelGenDay", 163840).getInt(163840);
         adminpanelGenNight = config.get("Light-Adbord Solar panel", "AdminPanelGenNight", 163840).getInt(163840);
         AdminpanelStorage = config.get("Light-Adbord Solar panel", "AdminPanelStorage", 20000000).getInt(20000000);
         AdminpanelOutput = config.get("Light-Adbord Solar panel", "AdminPanelOutput", 327680).getInt(327680);
         photonicpanelGenDay = config.get("Photonic Solar panel", "PhotonicPanelGenDay", 655360).getInt(655360);
         photonicpanelGenNight = config.get("Photonic Solar panel", "PhotonicPanelGenNight", 655360).getInt(655360);
         photonicpanelOutput = config.get("Photonic Solar panel", "PhotonicPanelOutput", 1310720).getInt(1310720);
         photonicpanelStorage = config.get("Photonic Solar panel", "PhotonicPanelStorage", 40000000).getInt(40000000);
         neutronpanelGenDay = config.get("Neutronium Solar panel", "NeutronPanelGenDay", 2621440).getInt(2621440);
         neutronpanelGenNight = config.get("Neutronium Solar panel", "NeutronPanelGenNight", 2621440).getInt(2621440);
         neutronpanelOutput = config.get("Neutronium Solar panel", "NeutronPanelOutput", 5242880).getInt(5242880);
         neutronpanelStorage = config.get("Neutronium Solar panel", "NeutronPanelStorage", 60000000).getInt(60000000);
        
         spectralsaberactive1 = config.get("Quantum Saber", "QuantumSaber Damage Active", 40).getInt(40);
         spectralsabernotactive1 = config.get("Quantum Saber", "QuantumSaber Damage Not Active", 8).getInt(8);
         maxCharge1 = config.get("Quantum Saber", "SpectralSaber max Charge", 200000).getInt(200000);
         transferLimit1= config.get("Quantum Saber", "SpectralSaber transfer Limit", 15000).getInt(20000);
         tier1= config.get("Quantum Saber", "SpectralSaber tier", 4).getInt(4);
         energy= config.get("Neutronium generator", "Consumes energy to make 1 mb neutronim", 15625000.0F).getInt((int) 15625000.0F);
         spectralpanelstorage= config.get("Spectral Solar panel", "Spectral Solar panel Storage", 500000).getInt(500000);
         
         maxCharge = config.get("Spectral Saber", "SpectralSaber max Charge", 600000).getInt(300000);
         transferLimit= config.get("Spectral Saber", "SpectralSaber transfer Limit", 40000).getInt(20000);
         tier_Saber= config.get("Spectral Saber", "SpectralSaber tier", 5).getInt(5);
         spectralsaberactive = config.get("Spectral Saber", "SpectralSaber Damage Active", 60).getInt(60);
         spectralsabernotactive = config.get("Spectral Saber", "SpectralSaber Damage Not Active", 12).getInt(12);
       
        
         enegry1= config.get("Imroved MFSU", "energy transfer Et/t", 32768).getInt(32768);
         storage1= config.get("Imroved MFSU", "energy storage", 100000000).getInt(100000000);
        tier2_MFSU= config.get("Imroved MFSU", "tier", 5).getInt(5);
         enegry2= config.get("Advanced MFSU", "energy transfer Et/t", 242144).getInt(242144);
         storage2= config.get("Advanced MFSU", "energy storage", 400000000).getInt(400000000);
         tier2= config.get("Advanced MFSU", "tier", 6).getInt(6);
         singularpaneltier= config.get("Singular Solar panel", "tier", 7).getInt(7);
         spectralpaneltier= config.get("Spectral Solar panel", "tier", 5).getInt(5);
         adminpaneltier= config.get("Light-Adbord Solar panel", "tier", 8).getInt(8);
         photonicpaneltier= config.get("Photonic Solar panel", "tier", 9).getInt(9);
         neutronpaneltier= config.get("Neutronium Solar panel", "tier", 10).getInt(10);
         
         //
         InfinityGenDay = config.get("Infinity Solar panel", "GenDay", 1048576).getInt(1048576);
         InfinityGenNight = config.get("Infinity Solar panel", "GenNight", 1048576).getInt(1048576);
         InfinityOutput = config.get("Infinity Solar panel", "Output", 2097152).getInt(2097152);
         InfinityStorage= config.get("Infinity Solar panel", "Storage", 30000000).getInt(30000000);
         
         tier = config.get("Neutron Solar panel(Avaritia)", "tier", 8).getInt(8);
         neutrongenday = config.get("Neutron Solar panel(Avaritia)", "GenDay", 1310720).getInt(1310720);
         neutronGenNight = config.get("Neutron Solar panel(Avaritia)", "GenNight", 1310720).getInt(1310720);
         neutronOutput = config.get("Neutron Solar panel(Avaritia)", "Output", 2621440).getInt(2621440);
         neutronStorage = config.get("Neutron Solar panel(Avaritia)", "Storage", 40000000).getInt(40000000);
         percent_output= config.get("Modules", "percent output", 20).getInt(20);
         percent_storage= config.get("Modules", "percent storage", 20).getInt(20);
         percent_day= config.get("Modules", "percent generation day", 20).getInt(20);
         percent_night= config.get("Modules", "percent generation night", 20).getInt(20);
//
         Storagequantumsuit=config.get("Battery", "MaxEnergy", 100000000).getInt(100000000);
         //
         tier3_MFSU= config.get("Advanced MFSU", "tier", 6).getInt(6);
         singularpaneltier= config.get("Singular Solar panel", "tier", 7).getInt(7);
         spectralpaneltier= config.get("Spectral Solar panel", "tier", 5).getInt(5);
         adminpaneltier= config.get("Light-Adbord Solar panel", "tier", 8).getInt(8);
         photonicpaneltier= config.get("Photonic Solar panel", "tier", 9).getInt(9);
         neutronpaneltier= config.get("Neutronium Solar panel", "tier", 10).getInt(10);
 	 //
          registerDraconicPanels= config.get("Draconic Integration", "Register Draconic Panels", true).getBoolean(true);
         registerChaosArmour = config.get("Draconic Integration", "Register Chaos Armour", true).getBoolean(true);
         registerChaosFluxCapacitor = config.get("Draconic Integration", "Register Chaos Flux Capacitor", true).getBoolean(true);
         registerChaosDestructionStaff = config.get("Draconic Integration", "Register Chaos Destruction Staff", true).getBoolean(true);
         registerChaosPickaxe = config.get("Draconic Integration", "Register Chaos Pickaxe", true).getBoolean(true);
         registerChaosShovel = config.get("Draconic Integration", "Register Chaos Shovel", true).getBoolean(true);
         registerChaosSword = config.get("Draconic Integration", "Register Chaos Sword", true).getBoolean(true);
         registerChaosBow = config.get("Draconic Integration", "Register Chaos Bow", true).getBoolean(true);
         registerChaosAxe = config.get("Draconic Integration", "Register Chaos Axe", true).getBoolean(true);
         nightvision= config.get("Events", "If player have quantum or nano or improvemed helmet and it was dressed and if player has coord y < 60 and skylight < 8,nightvision allow", true).getBoolean(true);
         disableeffect = config.get("Disable Effect", "Disable fireResistance", false).getBoolean(false);
         disableeffect1 = config.get("Disable Effect", "Disable waterBreathing", false).getBoolean(false);
         disableeffect2 = config.get("Disable Effect", "Disable jump", false).getBoolean(false);
         disableeffect3 = config.get("Disable Effect", "Disable moveSpeed", false).getBoolean(false);
         thaumcraft= config.get("Integrestion", "Integrestion Thaumcraft", false).getBoolean(false);
         wireless = config.get("Integrestion", "Integrestion Wireless Solar Panels", false).getBoolean(false);
         Draconic = config.get("Integrestion", "Integrestion Draconic Evolution", true).getBoolean(true);
         Botania = config.get("Integrestion", "Integrestion Botania", true).getBoolean(true); 
         Avaritia = config.get("Integrestion", "Integrestion Avaritia", true).getBoolean(true); 
       
         advGenDay = config.get("general", "AdvancedSPGenDay", 10).getInt(10);
         advGenNight = config.get("general", "AdvancedSPGenNight", 5).getInt(5);
         advStorage = config.get("general", "AdvancedSPStorage", 3200).getInt(3200);
         advOutput = config.get("general", "AdvancedSPOutput", 20).getInt(20);
         hGenDay = config.get("general", "HybrydSPGenDay", 40).getInt(40);
         hGenNight = config.get("general", "HybrydSPGenNight", 20).getInt(20);
         hStorage = config.get("general", "HybrydSPStorage", 10000).getInt(10000);
         hOutput = config.get("general", "HybrydSPOutput", 80).getInt(80);
         uhGenDay = config.get("general", "UltimateHSPGenDay", 160).getInt(160);
         uhGenNight = config.get("general", "UltimateHSPGenNight", 80).getInt(80);
         uhStorage = config.get("general", "UltimateHSPStorage", 100000).getInt(100000);
         uhOutput = config.get("general", "UltimateHSPOutput", 320).getInt(320);
         qpGenDay = config.get("general", "QuantumSPGenDay", 640).getInt(640);
         qpGenNight = config.get("general", "QuantumSPGenNight", 320).getInt(320);
         qpStorage = config.get("general", "QuantumSPStorage", 200000).getInt(200000);
         qpOutput = config.get("general", "QuantumSPOutput", 1280).getInt(1280);
      //
         TerrasteelRodHeat = config.get("TerrasteelRod", "Heat", 1).getInt(1);
         TerrasteelRodCells = config.get("TerrasteelRod", "Cells", 20000).getInt(20000);
         TerrasteelPower = config.get("TerrasteelRod", "Power", 2).getInt(2);
         //
         toriyRodHeat = config.get("ToriyRod", "Heat", 1).getInt(1);
         toriyRodCells = config.get("ToriyRod", "Cells", 10000).getInt(10000);
         toriyPower = config.get("ToriyRod", "Power", 1).getInt(1);
         //
         ProtonRodHeat = config.get("ProtonRod", "Heat", 1).getInt(1);
         ProtonRodCells = config.get("ProtonRod", "Cells", 30000).getInt(30000);
         ProtonPower = config.get("ProtonRod", "Power", 4).getInt(4);
         //
         Radius = config.get("Iridium rotor", "Radius", 11).getInt(11);
         durability = config.get("Iridium rotor", "durability", 648000).getInt(648000);
         efficiency = config.get("Iridium rotor", "efficiency", 2.0F).getInt((int) 2.0F);
         minWindStrength = config.get("Iridium rotor", "minWindStrength", 25).getInt(25);
         maxWindStrength = config.get("Iridium rotor", "maxWindStrength", 110).getInt(110);
         //
         Radius1 = config.get("Compress Iridium rotor", "Radius", 11).getInt(11);
         durability1 = config.get("Compress Iridium rotor", "durability", 720000).getInt(720000);
         efficiency1 = config.get("Compress Iridium rotor", "efficiency", 3.0F).getInt((int) 3.0F);
         minWindStrength1 = config.get("Compress Iridium rotor", "minWindStrength", 25).getInt(25);
         maxWindStrength1 = config.get("Compress Iridium rotor", "maxWindStrength", 110).getInt(110);
         //
         Radius2 = config.get("Spectral rotor", "Radius", 11).getInt(11);
         durability2 = config.get("Spectral rotor", "durability", 172800).getInt(172800);
        efficiency2 = config.get("Spectral rotor", "efficiency", 4.0F).getInt((int) 4.0F);
         minWindStrength2 = config.get("Spectral rotor", "minWindStrength", 25).getInt(25);
         maxWindStrength2 = config.get("Spectral rotor", "maxWindStrength", 110).getInt(110);
         Streak = config.get("Quantum Armor", "Allow Streak", true).getBoolean(true); 
         //
         Radius5 = config.get("Myphical rotor", "Radius", 11).getInt(11);
         durability5 = config.get("Myphical rotor", "durability", 345600).getInt(345600);
         efficiency5 = config.get("Myphical rotor", "efficiency", 5.0F).getInt((int) 5.0F);
         minWindStrength5 = config.get("Myphical rotor", "minWindStrength", 25).getInt(25);
         maxWindStrength5 = config.get("Myphical rotor", "maxWindStrength", 110).getInt(110);
        
         //
         Radius4 = config.get("Neutron rotor", "Radius", 11).getInt(11);
         durability4 = config.get("Neutron rotor", "durability", 2764800).getInt(2764800);
         efficiency4 = config.get("Neutron rotor", "efficiency", 7.0F).getInt((int) 7.0F);
         minWindStrength4 = config.get("Neutron rotor", "minWindStrength", 25).getInt(25);
         maxWindStrength4 = config.get("Neutron rotor", "maxWindStrength", 110).getInt(110);
         //
         Radius3 = config.get("Photon rotor", "Radius", 11).getInt(11);
         durability3 = config.get("Photon rotor", "durability", 691200).getInt(691200);
         efficiency3 = config.get("Photon rotor", "efficiency", 6.0F).getInt((int) 6.0F);
         minWindStrength3 = config.get("Photon rotor", "minWindStrength", 25).getInt(25);
         maxWindStrength3 = config.get("Photon rotor", "maxWindStrength", 110).getInt(110);
         limit = config.get("Unifier panels", "Limit", 2).getInt(2); 
        //
         manasteelgenday= config.get("Manasteel Solar Panel", "genday", 160).getInt(160);
         manasteelgennight= config.get("Manasteel Solar Panel", "gennight", 80).getInt(80);
         manasteelstorage= config.get("Manasteel Solar Panel", "storage", 100000).getInt(100000);
         manasteeloutput= config.get("Manasteel Solar Panel", "output", 320).getInt(320);
         manasteeltier= config.get("Manasteel Solar Panel", "tier", 3).getInt(3);
         //
         elementiumgenday= config.get("Elementium Solar Panel", "genday", 1280).getInt(1280);
         elementiumgennight= config.get("Elementium Solar Panel", "gennight", 320).getInt(320);
         elementiumstorage= config.get("Elementium Solar Panel", "storage", 100000).getInt(100000);
         elementiumoutput= config.get("Elementium Solar Panel", "output", 2560).getInt(2560);
         elementiumtier= config.get("Elementium Solar Panel", "tier", 4).getInt(4);
         //
         terasteelgenday= config.get("Terasteel Solar Panel", "genday", 10240).getInt(10240);
         terasteelgennight= config.get("Terasteel Solar Panel", "gennight", 2560).getInt(2560);
         terasteelstorage= config.get("Terasteel Solar Panel", "storage", 200000).getInt(200000);
         terasteeloutput= config.get("Terasteel Solar Panel", "output", 20480).getInt(20480);
         terasteeltier= config.get("Terasteel Solar Panel", "tier", 5).getInt(5);
         //
        draconicgenday= config.get("Draconic Solar Panel", "genday", 40).getInt(40);
        draconicgennight= config.get("Draconic Solar Panel", "gennight", 10).getInt(10);
        draconicstorage= config.get("Draconic Solar Panel", "storage", 10000).getInt(10000);
        draconicoutput= config.get("Draconic Solar Panel", "output", 80).getInt(80);
        draconictier= config.get("Draconic Solar Panel", "tier", 2).getInt(2);
    //
         awakenedgenday= config.get("Awakaned Solar Panel", "genday", 163840).getInt(163840);
         awakenedgennight= config.get("Awakaned Solar Panel", "gennight", 81920).getInt(81920);
         awakenedstorage= config.get("Awakaned Solar Panel", "storage", 10000000).getInt(10000000);
         awakenedoutput= config.get("Awakaned Solar Panel", "output", 327680).getInt(327680);
         awakenedtier= config.get("Awakaned Solar Panel", "tier", 7).getInt(7);
         //
         chaosgenday= config.get("Chaos Solar Panel", "genday", 1310720).getInt(1310720);
         chaosgennight= config.get("Chaos Solar Panel", "gennight", 1310720).getInt(1310720);
         chaosstorage= config.get("Chaos Solar Panel", "storage", 50000000).getInt(50000000);
         chaosoutput= config.get("Chaos Solar Panel", "output", 2621440).getInt(2621440);
         chaostier= config.get("Chaos Solar Panel", "tier", 10).getInt(10);
         ASP = config.get("Integrestion", "Integrestion Advanced Solar Panels", true).getBoolean(true);
         
         armor_maxcharge= config.get("Improvemed Quantum Armor", "maxcharge exept Improvemed Quantum Body", 100000000).getInt(100000000);
         armor_transferlimit= config.get("Improvemed Quantum Armor", "transferlimit", 10000).getInt(10000);
         armor_tier = config.get("Improvemed Quantum Armor", "tier", 4).getInt(4);
         armor_maxcharge_body= config.get("Improvemed Quantum Armor", "maxcharge Improvemed Quantum Body", 300000000).getInt(300000000);
         //
     }
     catch (Exception e) {
         throw new RuntimeException(e);
     }
     finally {
         config.save();
     }
}

}
