package com.Denfop;

import com.Denfop.block.mechanism.BlockBaseMachine;
import com.Denfop.block.mechanism.BlockMoreMachine2;
import com.Denfop.item.base.ItemCable;

import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraftforge.fluids.Fluid;

public class SSPItem {
	public static Item dust;
	public static Block blockSSPSolarPanel;
	public static Item enderquantumcomponent;
	public static Item singularcore;
	public static Item spectralcore;
	public static Item photoniy;
	public static Item photoniy_ingot;
	public static Item quantumHelmet;
	public static Item quantumBodyarmor;
	public static Item quantumLeggings;
	public static Item quantumBoots;
	public static ItemStack quantumHelmet1;
	public static ItemStack quantumBodyarmor1;
	public static ItemStack quantumLeggings1;
	public static ItemStack quantumBoots1;
	public static Item nanoSaber;
	public static Item lightAlloy;
	public static Item quantumPack;
	public static Item accumulator;
	public static Item bigAccumulator;
	public static Item belt;
	public static Item quantumBox;
	public static Item nanoBox;
	public static Item toolBox;
	public static Item singularSolarHelmet;
	public static Item spectralSolarHelmet;
	public static ItemStack insulatedCopperCableBlock;
	public static ItemStack copperCableBlock;
	public static ItemStack copperCableItem;
	public static ItemStack insulatedCopperCableItem;
	public static Item QuantumItems2;
	public static Item QuantumItems3;
	public static Item QuantumItems4;
	public static Item QuantumItems5;
	public static Item lapotronCrystal;
	public static Item photoniccore;
	public static Item neutroniumcore;
	public static Item neutronium;
	public static Item neutroniumingot;
	public static Item QuantumItems6;
	public static Item QuantumItems7;
	public static Item admincore;
	public static ItemStack mfeUnit;
	public static ItemStack mfsUnit;
	public static ItemStack hvTransformer;
	public static ItemStack evTransformer;
	public static Block blockfluidbit;
	public static Fluid neutronium1 = new Fluid("neutronium1");
	public static Block blockfluidneutronium;
	public static ItemStack cell;
	public static Item cell_all;
	public static ItemStack uuMatterCell;
	public static ItemStack massFabricator;
	public static Block blockAdvSolarPanel;
	public static Item advancedSolarHelmet;
	public static Item hybridSolarHelmet;
	public static Item ultimateSolarHelmet;
	public static ItemStack ingotIridium;
	public static ItemStack itemIrradiantUranium;
	public static ItemStack itemEnrichedPhotoniyAlloy;
	public static ItemStack itemIrradiantGlassPane;
	public static ItemStack itemIridiumIronPlate;
	public static ItemStack itemReinforcedIridiumIronPlate;
	public static ItemStack itemIrradiantReinforcedPlate;
	public static ItemStack itemQuantumCore;
	public static ItemStack itemUranIngot;
	public static ItemStack itemUHSP;
	public static ItemStack itemMTCore;

	public static Block blockSSPSolarPanel1;

	public static ItemStack spectralcable;
	public static ItemStack protoncable;
	public static ItemStack singularcable;
	public static ItemStack photoniycable;
	public static ItemStack machine;
	public static ItemStack advancedMachine;
	public static ItemStack macerator;
	public static ItemStack extractor;
	public static ItemStack compressor;
	public static ItemStack inductionFurnace;
	public static ItemStack massFabricator1;
	public static ItemStack macerator1;
	public static ItemStack ironfurnace;
	public static ItemStack compressor1;
	public static ItemStack electroFurnace;
	public static ItemStack electroFurnace1;
	public static ItemStack metalformer;
	public static ItemStack metalformer1;
	public static ItemStack iridium;
	public static ItemStack compressiridium;
	public static ItemStack spectral;
	public static ItemStack reactorDepletedprotonSimple;
	public static ItemStack reactorDepletedprotonDual;
	public static ItemStack reactorDepletedprotonQuad;
	public static ItemStack reactorDepletedprotoneit;
	public static ItemStack reactorprotonSimple;
	public static ItemStack reactorprotonDual;
	public static ItemStack reactorprotonQuad;
	public static ItemStack reactorprotoneit;
	public static Item proton;
	public static Item protonshard;
	public static Item QuantumItems8;
	public static Item QuantumItems9;
	public static Item coal_chunk1;
	public static Item compresscarbon;
	public static Item compresscarbonultra;
	public static Item protoncore;
	public static Item nightlinse;
	public static Item sunlinse;
	public static Item rainlinse;
	public static ItemStack reactorCoolantsix;
	public static ItemStack reactorCoolanttwelve;
	public static ItemStack reactorCoolantmax;
	public static Item aerlinse;
	public static Item earthlinse;
	public static Item netherlinse;
	public static Item endlinse;
	public static Item nanoSaber1;
	public static Block wolframore;
	public static Block chromiumore;
	public static Block platiumore;
	public static Block silverore;
	public static Block magnesiumore;
	public static Block mikhail_ore;
	public static Block spinelore;

	public static Item ultDDrill;
	public static ItemStack module61;
	public static ItemStack module62;
	public static ItemStack module63;
	public static ItemStack module65;
	public static ItemStack module66;
	public static ItemStack module64;
	public static ItemStack module67;
	public static ItemStack module68;
	public static ItemStack module69;
	public static ItemStack module70;

	public static Item module8;
	public static ItemStack module71;
	public static ItemStack module72;
	public static ItemStack module73;
	public static ItemStack module74;
	public static ItemStack module75;

	public static ItemStack overclockerUpgrade;
	public static ItemStack overclockerUpgrade1;
	public static Block iridiumore;
	public static Item iridium_nugget;
	public static Item michail_plate;
	public static Item mikhail_ingot;
	public static Item mikhail_nugget;
	public static Item chromium_plate;
	public static Item chromium_nugget;
	public static Item chromium_ingot;
	public static Item wolfram_nugget;
	public static Item spinel_plate;
	public static Item spinel_nugget;
	public static Item spinel_ingot;
	public static Item platium_plate;
	public static Item platium_nugget;
	public static Item platium_ingot;
	public static Item wolfram_ingot;
	public static ItemStack alloymachine;
	public static Item photoniyglass1;
	public static Item photoniyglass5;
	public static Item photoniyglass4;
	public static Item photoniyglass3;
	public static Item photoniyglass2;
	public static Item photoniyglass10;
	public static Item photoniyglass9;
	public static Item photoniyglass8;
	public static Item photoniyglass7;
	public static Item photoniyglass6;
	public static ItemStack goldCableItem;
	public static ItemStack doubleInsulatedGoldCableItem;
	public static ItemStack insulatedGoldCableItem;
	public static ItemStack ironCableItem;
	public static ItemStack tinCableItem;
	public static ItemStack doubleInsulatedIronCableItem;
	public static ItemStack insulatedIronCableItem;
	public static ItemStack glassFiberCableItem;
	public static ItemStack trippleInsulatedIronCableItem;
	public static ItemStack insulatedTinCableItem;
	public static ItemStack splitterCableItem;
	public static ItemStack detectorCableItem;
	public static ItemStack goldCableBlock;
	public static ItemStack doubleInsulatedGoldCableBlock;
	public static ItemStack insulatedGoldCableBlock;
	public static Block BlockCable;
	public static ItemStack ironCableBlock;
	public static ItemStack doubleInsulatedIronCableBlock;
	public static ItemStack trippleInsulatedIronCableBlock;
	public static ItemStack splitterCableBlock;
	public static ItemStack insulatedtinCableBlock;
	public static ItemStack detectorCableBlock;
	public static ItemStack tinCableBlock;
	public static ItemStack glassFiberCableBlock;
	public static ItemStack insulatedIronCableBlock;
	public static ItemStack constructionFoam;
	public static ItemStack constructionFoamWall;
	public static ItemStack ChargepadmfsUnit;
	public static ItemStack ChargepadmfeUnit;
	public static Block endgold_stone;
	public static Block nethergoldrack;
	public static Block netherironrack;
	public static Block endiron_stone;
	public static Block netherlapisrack;
	public static Block endlapis_stone;
	public static Block netherredstonerack;
	public static Block endredstone_stone;
	public static Block nethercoalrack;
	public static Block endcoal_stone;
	public static Block netherdiamondrack;
	public static Block enddiamond_stone;
	public static Block netheremeraldrack;
	public static Block endemerald_stone;
	public static Block netherleadrack;
	public static Block endlead_stone;
	public static Block nethertinrack;
	public static Block endtin_stone;
	public static Block netheruranrack;
	public static Block enduran_stone;
	public static Block nethercopperrack;
	public static Block endcopper_stone;

	public static Block endchromium_stone;
	public static Block endiridium_stone;
	public static Block endmagnesium_stone;
	public static Block endmikhail_stone;
	public static Block endplatium_stone;
	public static Block endwolfram_stone;
	public static Block netherchromiumrack;
	public static Block netheriridiumrack;
	public static Block nethermagnesiumrack;
	public static Block nethermikhailrack;
	public static Block netherplatiumrack;
	public static Block netherspinelrack;
	public static Block netherwolfram_rack;
	public static Block endspinel_stone;
	
	public static Item advanced_core;
	public static Item hybrid_core;
	public static Item ultimate_core;
	public static Block blockadmin;
	public static Item module;
	public static Item module1;
	public static Item module2;
	public static Item module3;
	public static Item module4;
	public static Item module5;
	public static Item module6;
	public static Item module7;

	public static Item wolfram_plate;
	public static ItemCable cable;
	public static Item itemSSP;
	public static BlockBaseMachine machine1;
	public static Block blocksintezator;

	public static Item magnesium_ingot;
	public static Item magnesium_plate;
	public static Item magnesium_nugget;
	public static Block toriyore;
	public static Item toriy;
	public static Item chromiumcrushedore;
	public static Item electriumdust;
	public static Item electriumingot;
	public static Item electriumplate;
	public static Item blast;
	public static Item invardust;
	public static Item invaringot;
	public static Item invarplate;
	public static Item nickel;
	public static Item nickelplate;
	public static Item michalovcrushedore;
	public static Block nicelore;
	public static Block magnetitore;
	public static ItemStack reactorDepletedtoriySimple;
	public static ItemStack reactorDepletedtoriyDual;
	public static ItemStack reactorDepletedtoriyQuad;
	public static ItemStack reactortoriySimple;
	public static ItemStack reactortoriyDual;
	public static ItemStack reactortoriyQuad;
	public static Item iridiumcrushedore;
	public static Item wolframcrushedore;
	public static Item magnesiumcrushedore;
	public static Item nickelcrushedore;
	public static Item platiumcrushedore;
	public static Item spinelcrushedore;
	public static Item updatekits;
	public static ItemStack photon;
	public static ItemStack neutron;
	public static ItemStack myphical;

	public static Block machines;
	public static Block electricblock;
	public static Item matter;
	public static ItemStack massFabricator2;
	public static ItemStack massFabricator3;
	public static ItemStack generationmicrochip;
	public static ItemStack moleculartransformer;
	public static Block machines_base;
	public static Block Chargepadelectricblock;
	public static Block cableblock;

	public static ItemStack glassFiberCableItem1;

	public static Block machines_base1;

	public static Item caravky_ingot;

	public static Block electricblock1;

	public static ItemStack mfeUnit1;

	public static ItemStack mfsUnit1;

	public static Item module9;

	public static Item nanopickaxe;

	public static Item nanoshovel;

	public static Item nanoaxe;

	public static Item quantumpickaxe;

	public static Item quantumshovel;

	public static Item quantumaxe;

	public static Item spectralpickaxe;

	public static Item spectralshovel;

	public static Item spectralaxe;
	public static ItemStack barionrotor;
	public static ItemStack adronrotor;
	public static ItemStack sprengerrotor;
	
}
